/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_JNIFilter */

#ifndef _Included_jni_JNIFilter
#define _Included_jni_JNIFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_JNIFilter
 * Method:    filter
 * Signature: ([Ljava/lang/String;[[I[[D[Ljava/lang/String;[II[[I[[D[[I[[DI)[I
 */
JNIEXPORT jintArray JNICALL Java_jni_JNIFilter_filter
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jintArray, jint, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jint);

/*
 * Class:     jni_JNIFilter
 * Method:    sort
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_jni_JNIFilter_sort
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
