/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_JNIExec */

#ifndef _Included_jni_JNIExec
#define _Included_jni_JNIExec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_JNIExec
 * Method:    exec
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_jni_JNIExec_exec
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
